### ISSUE TITLE
[BUG] Processes launched by rofi displayed as "Rofi" under system monitor (`plasma-systemmonitor 5.25.4-1`)

### ISSUE THREAD

**Issue by 5HT2** [davatorium/rofi#1701] opened 2022-09-08 00:12 UTC
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://cdn.l1v.in/paste-1662595580.txt

### Theme

https://cdn.l1v.in/paste-1662595586.txt

### Launch command

`rofi -show combi`

### Step to reproduce

* Launch app with rofi
* Launch other app with rofi
* Look for their resource usage in system monitor (`plasma-systemmonitor 5.25.4-1`)

### Expected behavior

I would expect them to be launched as their own respective applications. Other application launchers don't have this behavior. 

### Actual behavior

They show up as rofi.

### Additional information

I'm not sure whether to file this under system monitor or under rofi - I felt like filing this bug here makes more sense given it's related to the behavior of how rofi launches applications. 

Also related, in Tree mode in htop, applications launched by rofi are under the user session tree as you would expect them to but filtering by `rofi` with F4 locates them, I have no idea what metadata htop is matching there.

**Comment by DaveDavenport** [comment] 2022-09-08 07:35
in htop, for me it does not show them under rofi (unless they have the string `rofi` in their name).
plasma-systemmonitor I am unsure how it works..  for me it shows 0 applications and under processes it shows all processes as 
expected.
I have no idea how this 'applications'  thing should work, as it does nothing for me. Is this where you are looking? 

I totally do not see this behaviour when I go through the process tree of an application launched via rofi. (via htop, /proc, gnome-system-monitor, etc.)

Rofi uses https://docs.gtk.org/glib/func.spawn_async.html  to launch the application and tries to do the right 'startup notification' procedure.

**Comment by 5HT2** [comment] 2022-09-11 19:57
Here's a screengrab from system-monitor.

These are all distinct processes and I can guess which each one is by closing them (firefox, discord, etc, just high resource use ones ones at the top.

![](https://frogg.ie/VyD)

**Comment by DaveDavenport** [comment] 2022-09-12 07:09
no idea how that 'applications' thing work. I does not seem to use the normal process tree. 
The whole applications panel/tab is empty for me.

what does it show under 'processes'

**Comment by DaveDavenport** [comment] 2022-09-12 07:29
@sardemff7  could this be because of the startup notification implementation?

**Comment by 5HT2** [comment] 2022-09-12 08:37
@DaveDavenport 
> what does it show under 'processes'

It does not have this issue.

![](https://frogg.ie/X32)

**Comment by DaveDavenport** [comment] 2022-09-12 08:50
So the process name is fine and not changed.  So it is something the magic 'applications' thing does.

**Comment by 5HT2** [comment] 2022-09-12 23:23
I think applications is grouping the subprocesses of each process to display their combined resource use as one.

**Comment by DaveDavenport** [comment] 2022-09-13 06:46
I don't think so.  for me applications launched using rofi do not show up as subprocess of rofi.
look at f.e. pstree.

**Comment by 5HT2** [comment] 2022-09-13 21:14
> I don't think so. for me applications launched using rofi do not show up as subprocess of rofi. look at f.e. pstree.

<details><summary><b>Package details</b></summary>

```
plasma-systemmonitor 5.25.5-1
psmisc 23.5-1
htop 3.2.1-1
```

</details>

<details><summary><b>KDE Details</b></summary>

```
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.6
Kernel Version: 5.19.7-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-8665U CPU @ 1.90GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: LENOVO
Product Name: 20QD000LUS
System Version: ThinkPad X1 Carbon 7th
```

</details>

---

`pstree`: ![](https://frogg.ie/VBu)

---

`system-monitor` overview: ![](https://frogg.ie/y8m)

---

`system-monitor` processes: ![](https://frogg.ie/i5i)

---

`htop`: ![](https://frogg.ie/X39)

**Comment by 5HT2** [comment] 2022-09-20 18:18
Any other information I can help provide?

**Comment by 5HT2** [comment] 2022-11-25 01:04
Any status on this? It doesn't appear to be fixed on latest versions of any of the aforementioned packages.

**Comment by DaveDavenport** [comment] 2022-11-25 10:33
No. I have no idea why kde for you behaves the way it does. I did not manage to reproduce this, so little I can do.

You could try launching clients in separate cgroups like this:
https://github.com/davatorium/rofi/pull/1752

But I have no idea if this is related, as I cannot reproduce.

Can you tell me how this 'applications'  thing works? where does it get it? how does it group?

**Comment by 5HT2** [comment] 2022-11-26 08:03
> Can you tell me how this 'applications' thing works? where does it get it? how does it group?

I'm not sure - but I can look at the source code myself and try to explain.

The table rendering is done here: https://github.com/KDE/plasma-systemmonitor/blob/master/src/faces/applicationstable/contents/ui/FullRepresentation.qml#L65

The name is parsed here: https://github.com/KDE/plasma-systemmonitor/blob/74878d37b669d86f820941d1216a3434467529f2/src/faces/applicationstable/contents/ui/ApplicationInformation.qml#L43

The columns, excluding the name, are declared here: https://github.com/KDE/plasma-systemmonitor/blob/74878d37b669d86f820941d1216a3434467529f2/src/faces/applicationstable/contents/ui/ApplicationDetails.qml#L62

`name` is passed into `sensorColumns` from `appName` here: https://github.com/KDE/plasma-systemmonitor/blob/74878d37b669d86f820941d1216a3434467529f2/src/faces/applicationstable/contents/ui/ApplicationsTableView.qml#L59

The `appName` is already populated in `appModel.availableAttributes`. 

Now, this is where I get lost. I don't know where `availableAttributes` is populated and it doesn't seem to be set in that codebase itself, it has to be part of a library (I think).

**Comment by 5HT2** [comment] 2022-11-26 08:07
Can you try using my `~/.config/rofi/` config? My rofi command is `rofi -show combi`. I'm unsure if it makes a difference at all.

`config.rasi`: https://cdn.l1v.in/paste-1669449994.txt
`colors-rofi-dark.rasi`: https://cdn.l1v.in/paste-1669450012.txt

**Comment by 5HT2** [comment] 2022-11-26 08:17
Hmn, I found a bug report for `plasma-systemmonitor` that references `ksysguard`: https://bugs.kde.org/show_bug.cgi?id=462044

It *might* be relevant, `libksysguard: crash in KSysGuard::SensorProperty::setName` implies that `setName` is being used to set the name that we're after here, given the application table rendering is just referring to the original sensors.

**Comment by DaveDavenport** [comment] 2022-11-26 09:18
I don't need to know how the ui of sytemmonitor is build up, I need to know how it gets the information .

Can you *please* try the linked documentation to launch applications in their own cgroup. I suspect it might be related to that.

**Comment by 5HT2** [comment] 2022-11-27 09:59
> I need to know how it gets the information .

That's mostly why I was looking at it's code, unfortunately I couldn't figure out where `availableAttributes` was being set with the process info, just that it contained it.

I'll try the cgroup thing now and let you know if it helps.

**Comment by 5HT2** [comment] 2022-11-27 10:02
Issue is somewhat fixed when using a cgroup (`org.rofi.intellij-idea-ultimate-edition` was the application I tried below, normally it would just show Rofi). 

I'd expect a pretty name and icon like Dolphin and Libreoffice have, but it's better than nothing for now. If this helps and there's patches I can test for you to fix the issue within rofi (and hopefully also get the nice names / icons working) I'd be happy to!

![](https://frogg.ie/aOW)

**Comment by DaveDavenport** [comment] 2022-11-27 15:00
Closing, as not a bug (rofi does not have/claim cgroup support). 
(portable) PRs for improvement welcome.

**Closed as completed by DaveDavenport** 2022-11-27 15:00 UTC
Labels: bug
