### ISSUE TITLE
[BUG] how to use ROFI_DATA?

### ISSUE THREAD

**Issue by dongho-jung** [davatorium/rofi#1632] opened 2022-05-10 17:31 UTC
### Rofi version (rofi -v)

1.7.3

### Configuration

https://gist.github.com/0xF4D3C0D3/c64497f4879683fc3557afc2f2792502

### Launch command

rofi -show $ -modi $:./foo.sh

### Step to reproduce

1. this is my foo.sh
```sh
#!/bin/bash

echo -en "\x00data\x1fhello\n"

echo "my data: ${ROFI_DATA}"
echo "choose me!"
```

2. `chmod +x ./foo.sh`

2. I wanted to set ROFI_DATA somehow but it didn't work. ROFI_DATA is always empty

### Expected behavior

```
my data: hello
choose me!
```

or

```
my data:
choose me! <- choose

...

my data: hello
choose me!
```

well actually the latter one is what I want more

### Actual behavior

ROFI_DATA is always empty.

```
my data:
choose me!
```

or

```
my data:
choose me! <- choose

...

my data:
choose me!
```

### Additional information

I tested this also with [Examples/test_script_env.sh](https://github.com/davatorium/rofi/blob/next/Examples/test_script_env.sh) but its result is the same as here.

**Comment by dongho-jung** [comment] 2022-05-10 18:42
I worked around this as follows:

```
DATA_PATH=/tmp/rofi-data

read_data() {
    cat $DATA_PATH
}

write_data() {
    echo $1 > $DATA_PATH
}

if [ $ROFI_RETV -eq 0 ]; then write_data; fi
```

**Comment by DaveDavenport** [comment] 2022-05-10 19:48
1. Not an issue, its a question -> discussion forum
2. duplicate of #1625
3.  https://github.com/davatorium/rofi/discussions/1626

**Closed as completed** 2022-05-10 19:47 UTC
Labels: duplicate, Question (Please follow the guidelines)
