### ISSUE TITLE
Can't input words in chinese or japanse with fcitx

### ISSUE THREAD

**Issue by theFool32** [davatorium/rofi#483] opened 2016-10-16 07:09 UTC
## Version

1.2.0

arch+bspwm
## Configuration

[configuration](https://gist.github.com/theFool32/d4deb49c7a0da1d0023010a04d5d6deb)
## Launch Command

rofi -show run -lines 3
## Steps to reproduce

launch rofi and type words.
## What behaviour you see

can only input english letter. however, pasting chinese works.
## What behaviour you expect to see

works with chinese.
Thx. :smiley:

**Comment by DaveDavenport** [comment] 2016-10-16 08:12
@sardemff7  ideas?

Can you give more information about how to reproduce this? I never type chinese or heard of fcitx.

**Comment by theFool32** [comment] 2016-10-16 09:16
@DaveDavenport 
[fcitx](https://fcitx-im.org/) is an input method framework which i used to type chinese and japanse.
You can reproduce this by [installing fcitx](https://wiki.archlinux.org/index.php/Fcitx) and try to type chinese in rofi.

Or are there any successful example in typing other language?
Thank you.

ps. my locale setting here.
```
> locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

**Comment by DaveDavenport** [comment] 2016-10-16 11:11
Yes, I had people test different languages with different scripts before.

**Comment by DaveDavenport** [comment] 2016-10-16 12:17
I can confirm it does not work. Unsure why though, I have 0 knowledge about this :(

**Comment by sardemff7** [comment] 2016-10-16 12:21
Did it use to work?

On the Arch wiki, I see this export: `export XMODIFIERS=@im=fcitx`, does it help? I think not but it’s not hard to test.

AFAICT, rofi never supported XIM, nor any input method. That would need a whole new extension to support, so a lot of code.
[This is the spec](https://www.x.org/releases/X11R7.6/doc/libX11/specs/XIM/xim.html), as a potential starting point if anyone is willing to code it.

**Comment by theFool32** [comment] 2016-10-16 14:06
@sardemff7  I used rofi recently and find it doesn't work so I don't know whether it used to work.
` XMODIFIERS=@im=fcitx` has been set already so it may not help.

Thanks for replying.  :)

**Comment by MaskRay** [comment] 2017-03-11 20:38
I also want to type Chinese in rofi but xcb does not seem to support X Input Method....

**Comment by lulitao1997** [comment] 2018-01-13 09:26
Maybe add support for searching romanized CJK charater is a better way, because switching IME needs extra key input anyway.

For example, when searching for 终端（Terminal in Chinese）, we can input "zhong duan", which is a romanization for 终端.

Same goes for Japanese, searching 端末（Terminal in Japanese） can be done by searching "sankitsu".

As far as I know, softwares such as Spotlight, Alfred in macOS have similar behavior.

I will try implementing this functionality after 4 days or so.

**Comment by sardemff7** [comment] 2018-01-13 09:46
I would bet Mac OS X to have either an helper to get the romanized version, or better files to begin with, and the tool has very little to do for such a feature. I am not sure we can add that to rofi with less work than IME integration.

**Comment by balta2ar** [comment] 2018-01-23 17:39
Not sure if it helps anyhow, but just so you know, I can confirm that Korean input is not working either. I'm using ibus + ibus-hangul in ArchLinux (openbox) according to this guide: https://wiki.archlinux.org/index.php/Internationalization/Korean. It just won't switch to Hangul and would continue to type Latin characters. Pasting works, though.

**Comment by moorchegue** [comment] 2018-04-21 17:14
If anyone is looking for a dmenu replacement with XIM support, GTK+ based `gdmenu` did the trick for me. There's an AUR package for Archies.

**Comment by AkitakiKou** [comment] 2019-01-26 14:00
For those who are getting this issue, my personal workaround right now is to edit the `.desktop` entries with only Chinese / Japanese names, adding a `GenericName` property with the romanized version of their name to the applications. It then become searchable by using the roman name in rofi, with their `GenericName` being wrapped in parentheses after their `Name`. Not perfect, but at least it is usable.

**Comment by zhenjieliang** [comment] 2020-03-23 11:09
> For those who are getting this issue, my personal workaround right now is to edit the `.desktop` entries with only Chinese / Japanese names, adding a `GenericName` property with the romanized version of their name to the applications. It then become searchable by using the roman name in rofi, with their `GenericName` being wrapped in parentheses after their `Name`. Not perfect, but at least it is usable.

@AkitakiKou Thanks for your kindly reply!

But this solution works only when the desktop application has no more than 1 instance. For example, when opening multiple pdf whose names with chinese characters included with llpp pdf viewer, then searching "llpp" will have multiple choices.

Of course one can bypass this dilemma by changing the names of pdf files to roman names.

**Comment by amitbha** [comment] 2021-11-03 15:12
Not support IME is like not support utf-8.

**Comment by DaveDavenport** [comment] 2021-11-03 15:19
@amitbha  A patch to add IME support will be happily accepted.

As I mentioned before I have zero experience with it, nor am the right person to test it (as I never used it).

 Replying just to complain without contributing anything to the solution is like standing on the street corner shouting your coffee is to cold.

**Comment by moorchegue** [comment] 2021-11-03 16:12
That's an overstatement, of course. Most written languages require unicode support, yet most or them (even some languages with alphabets that exceed hundreds of characters) don't require any IME. That said, for a subset of people it's a daily necessity, and among them such feature would be highly appreciated. I'd totally help with testing it if there was a PR.

**Comment by yssource** [comment] 2021-12-02 02:07
I also want to type Chinese in rofi.

**Comment by DaveDavenport** [comment] 2021-12-02 08:24
closing and locking this because of pointless 'bumps' (see guidelines). 
A patch or PR would be highly appreciated.

**Closed by DaveDavenport** 2021-12-02 08:24 UTC
Labels: enhancement, Crazy/Future, Nice To Have

**Comment by DaveDavenport** [comment] 2022-11-08 18:19
Patch been merged!

**Comment by DaveDavenport** [comment] 2023-10-22 07:58
Link to PR: https://github.com/davatorium/rofi/pull/1735
