### ISSUE TITLE
[BUG] Rofi modi scripts terminating with SIG SEGV (Address Boundary Error)

### ISSUE THREAD

**Issue by gajeet11000** [davatorium/rofi#1928] opened 2023-12-17 06:59 UTC
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/gajeet11000/ed328a9c711616c9f7dc8e08ac3a4df9

### Theme

https://gist.github.com/gajeet11000/ab953c38a707d9170c32a41eb15f4da3

### Timing report

https://gist.github.com/gajeet11000/ec831acdc91b099e1e1f6ae91b1c3cfc

### Launch command

rofi -show "Home" -config /home/gajeet/.config/rofi/themes/search-config.rasi -theme ~/.config/rofi/themes/search.rasi -sort -sorting-method fzf -i -normal-window

### Step to reproduce

Here I'm using script based modi config file where there are two modi "Home" and "Storage" with their respective script paths, and here are the two scripts below:

**Home script**

```
#!/bin/bash
opener="xdg-open"

if [[ -z "$1" ]]; then
    fd . --hidden $HOME 2>/dev/null | sed "s;$HOME;~;g"
else
    selection=$(echo "$1" | sed 's;\~;$HOME; ;s/ /\\ /g; s/\&/\\&/g; s/(/\\(/g; s/)/\\)/g')
    eval $opener "$selection" > /dev/null 2>&1 &
fi
```

**Storage script**

```
#!/bin/bash
opener="xdg-open"

if [[ -z "$1" ]]; then
#Here mnt/Storage can be replaced with any valid path of your choice.
    fd . --hidden /mnt/Storage 2>/dev/null
else
    selection=$(echo "$1" | sed 's/ /\\ /g; s/\&/\\&/g; s/(/\\(/g; s/)/\\)/g')
    eval $opener "$selection" > /dev/null 2>&1 &
fi
```

**Step 1:** Save both the theme config and rofi config to their respective rasi files.

**Step 2:**  Save both the Home and Storage scripts to their respective sh file and make them executable.

**Step 3:** Edit the rofi config file and change the paths according to the paths of the shell script on your machine.

**Step 4:** Edit the paths for the config file and the theme file in the run command. Then run the command.

**Step 5:** When the window shows up with the prompt type something in the prompt and keep toggling between the Home and Search Modi using `Ctrl + Tab`. It should it terminated due to SIGSEGV (Address boundary error) Segmentation fault. If it doesn't try changing the prompt input string and repeat the same.

### Expected behavior

The expected behavior is that rofi must not terminate with a SIGSEGV error and smoothly toggle between the configured modi

### Actual behavior

Rofi terminates with the following error:

fish: Job 1, 'G_MESSAGES_DEBUG=Timings rofi -…' terminated by signal SIGSEGV (Address boundary error)

### Additional information

Before posting this issue, I had previously asked for help on the ArchLinux forum. Here is the [link](https://bbs.archlinux.org/viewtopic.php?id=291105)  . It will be very helpful for you guys as I have found out where the error occurs using the gdb debugging tool, must check it out. Here is the output of the [Debuginfod](https://gist.github.com/gajeet11000/e76a1ebe0775ada9eca7a899a4eb3d1d)

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment] 2023-12-17 07:45
Thanks for the backtrace.

**Comment by DaveDavenport** [comment] 2023-12-17 12:16
Can you test with git?  I can reproduce with 1.7.5 but not head of git.

**Comment by gajeet11000** [comment] 2023-12-17 13:05
By the head of the git you mean the latest commit on the repo, right?

Sure, let me install the checkout from the git, build, and test it.

**Comment by gajeet11000** [comment] 2023-12-17 13:41
Yes, I am able to reproduce it with the latest head of git

Version: 1.7.5-188-gd042e20f (next)

```
Thread 1 "rofi" received signal SIGSEGV, Segmentation fault.
_get_display_value (sw=0x555555618cf0, selected_line=267142, 
    state=0x7fffffffdb08, list=0x7fffffffdb10, get_entry=1)
    at ../source/modes/script.c:436
436	 if (pd->cmd_list[selected_line].urgent) {
```

Link to the [backtrace](https://gist.github.com/gajeet11000/8b2520f7133e49ceb98b45b16c0ca44e)

**Comment by DaveDavenport** [comment] 2023-12-17 16:13
Thanks again for the backtrace, that is very helpfull.
I think I see what is going wrong (not yet why).

**Comment by DaveDavenport** [comment] 2023-12-17 16:31
^^ might fix it, if I understood problem correct. (hard when I cannot reproduce).

**Comment by gajeet11000** [comment] 2023-12-20 03:56
Apologies for my late response. Yes, it is fixed now!! I tested it, and it works fine with no issues. Will this fix also be released as an update in the Linux official packages?

Thank you so much ^-^

**Comment by DaveDavenport** [comment] 2023-12-20 07:25
It will be included in next release of rofi.

I not sure what is 'linux official packages' .

**Closed as completed by DaveDavenport** 2023-12-20 07:25 UTC
Labels: bug

**Comment by gajeet11000** [comment] 2023-12-20 07:40
Yes, it's not Linux's official package. Sorry for the wording; I meant the Rofi, which is available through Pacman or Apt Package Managers.

**Comment by DaveDavenport** [comment] 2023-12-20 22:24
I have 0 input on distributions packages and no time to chase maintainers.
Regrettable whatever version winds up in X is what it is.
