### ISSUE TITLE
[BUG] There's a slight delay when "combi" is the first to show

### ISSUE THREAD

**Issue by alienbogart** [davatorium/rofi#1674] opened 2022-08-14 18:46 UTC
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/alienbogart/849bb100bf1e8f8fa3e531937cfad011

### Launch command

rofi -show

### Step to reproduce

* Run the commend `rofi -show`
* Run the command `rofi -show combi -combi-modi run,drun`

The second command should run considerably than the first.

### Expected behavior

The command `rofi -show combi -combi-modi run,drun` should not take so long to display rofi.

### Actual behavior

The command `rofi -show combi -combi-modi run,drun` takes significantly longer to display rofi.

### Additional information

* Version of Manjaro:
``` 
$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.6
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux"
```

* Version of XFCE:
```
xfdesktop --version
This is xfdesktop version 4.16.0, running on Xfce 4.16.
Built with GTK+ 3.24.29, linked with GTK+ 3.24.34.
Build options:
    Desktop Menu:        enabled
    Desktop Icons:       enabled
    Desktop File Icons:  enabled
```

**Comment by DaveDavenport** [comment] 2022-08-14 20:41
combi mode does nothing except call drun/run. It is unlikely to cause the slowness.

Can you please get a timing log?  (https://github.com/davatorium/rofi/blob/next/doc/rofi-debugging.5.markdown#timing-traces) when calling your launch command.

For me there is no difference between

rofi -show drun -modes drun,run

vs 
rofi -show combi -modes combi -combi-modes drun,run

**Comment by DaveDavenport** [comment] 2022-08-14 20:53
> The second command should run considerably than the first.

What do you mean with this?  your 2nd command, given your config, loads more modes, then the first. (window, run, drun vs   window,run).

(this is the warning rofi prints on your command:
> Mode combi is not enabled. I have enabled it for now.
> Please consider adding combi to the list of enabled modes: modes: [window,run,combi].

)

**Comment by DaveDavenport** [comment] 2022-08-19 18:13
closing, requested info not provided and unable to reproduce.

**Closed as completed by DaveDavenport** 2022-08-19 18:13 UTC
Labels: bug
