### ISSUE TITLE
[BUG] Weird visual glitch when using the emoji plugin

### ISSUE THREAD

**Issue by madprops** [davatorium/rofi#2036] opened 2024-10-03 11:14 UTC
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/madprops/fb40662a5eb644dcfcd931b14ba5e8ab

### Theme

https://gist.github.com/madprops/3ab74683add2faebfbb44a411a35722d

### Launch command

rofi -modi emoji -show emoji

### Step to reproduce

Search for `skull`

![skullemoji](https://github.com/user-attachments/assets/788000a1-aff7-4f9c-ab86-808f64cad16f)

As you can see below the first item, the second item looks weird.

Is that a rofi bug?

### Expected behavior

No glitch.

### Actual behavior

Glitch.

### Additional information

I'm using the emoji plugin.

Which I think is this one: https://archlinux.org/packages/extra/x86_64/rofi-emoji/

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment] 2024-10-03 11:51
This is *kinda* a rofi bug..   rofi determines the size of a row in the listview based by creating a row and getting the size of the widget..
This is computed based on the pixel extend pango returns for a small string ("aAjb")  this is then saved so it can pre-compute everything. This is for speed reasons.

If fonts has, mostly with icons, suddenly a glyph that is bigger then expected, this happens.
Last time I looked (years ago) there was not a quick way to find the largest glyph in available.

**Comment by DaveDavenport** [comment] 2024-10-03 15:33
Pushed possible fix, if this does not fix it, I am not sure if it is easily fixable in rofi.

**Comment by xsy420** [comment] 2024-10-17 14:36
I build it with commit [186b0e7b](https://github.com/davatorium/rofi/commit/186b0e7be01868821907bd76cc83f6a3d4c66f9f).
when I run rofi -show drun, it receive a segmentation fault. 
[gdb.log](https://github.com/user-attachments/files/17414139/gdb.log)
build command
```bash
autoreconf -i
./configure --prefix=/usr --sysconfdir=/etc --enable-imdkit
make
```

**Comment by DaveDavenport** [comment] 2024-10-17 20:24
Thanks for testing and the trace.

**Comment by DaveDavenport** [comment] 2024-10-17 20:34
To bad I am missing entries from the trace that crashes.
I don't really see how we can get this crash, with the newly added code (unless its an issue in pango). 
Hope I can reproduce.

**Comment by DaveDavenport** [comment] 2024-10-17 20:41
What distro are you using?

**Comment by xsy420** [comment] 2024-10-17 22:46
I'm using Arch Linux

**Comment by xsy420** [comment] 2024-10-18 07:52
well, it's because variable name redefined.
at line 129 in textbox.c: 
```c
  const char *font = rofi_theme_get_string(WIDGET(tb), "font", NULL);
```
but at line 147
```c
 PangoFont *font = pango_context_load_font(p_context, tbfc->pfd);
```
I tried  rename to pfont it works (no segmentation fault at least)
```c
        PangoFont *pfont = pango_context_load_font(p_context, tbfc->pfd);
        if (pfont) {
          PangoFontMetrics *fm = pango_font_get_metrics(pfont, NULL);
          if (fm) {
            int h = pango_font_metrics_get_height(fm) / PANGO_SCALE;
            if (h > 0) {
              tbfc->height = h;
            }
            pango_font_metrics_unref(fm);
          }
          g_object_unref(pfont);
        }
```

**Comment by DaveDavenport** [comment] 2024-10-18 20:00
aah stupid error by me,  Thanks!

(/me goes to add -Wshadow to compile flags)

**Comment by DaveDavenport** [comment] 2024-12-25 18:42
Any update if the commit fixes the reported glitch ?

**Comment by madprops** [comment] 2024-12-25 21:12
Arch is still packaging an older version I think `1.7.5-3` - The glitch on the emoji picker is still present.

**Comment by DaveDavenport** [comment] 2024-12-25 21:22
![rofi-2024-12-25-2221-00000](https://github.com/user-attachments/assets/c2bb68d7-7ab6-41f2-a44b-ae5714ee5200)

It seems not to fix it..

**Comment by DaveDavenport** [comment] 2024-12-25 21:41
Debugging further, the FontMetrics used by rofi to find the size, return that the distance between baselines is 22 px.. while that icon is 24 pixels high..

The bounding box for ☠  is 49.
If I use that  for every row it also is very odd..

**Comment by DaveDavenport** [comment] 2024-12-25 21:46
![rofi-2024-12-25-2245-00000](https://github.com/user-attachments/assets/1638eb2f-ff41-4303-98f6-59fb374debea)

You can see only the ☠ is normal...    I think there is not an easy fix for this.

**Comment by DaveDavenport** [comment] 2024-12-26 13:45
Gave it some more thought.. I am closing this issue, I am pretty sure there is very little I can do about this beside having dynamic row height.  I want to avoid this as it makes the logic in rofi more difficult and might slow it down (I need to implement this at some point to see what the impact is).

**Closed as not planned by DaveDavenport** 2024-12-26 13:45 UTC
Labels: bug
