### ISSUE TITLE
[REQUEST] keyboard iddle seconds instead Enter-Key

### ISSUE THREAD

**Issue by sl5net** [davatorium/rofi#1211] opened 2020-10-10 19:59 UTC
Motivation:

Today, computers are an integral part of our work and personal lives. It is unimaginable to function without one, however, the long hours spent typing on a keyboard can lead to aching hands. Thankfully, there are many ways to tackle the pain you experience.
**Thanks too your rofi!!!!**

i use [<kbd>Alt</kbd>+<kbd>TAB</kbd>](https://askubuntu.com/questions/1281728/assign-shortcut-key-alttab-to-run-a-script-in-kubuntu-from-ubunto) to start `rofi -show window`.

often i just switch to last window by using: 
1. <kbd>Alt</kbd>+<kbd>TAB</kbd>
1. <kbd>Enter</kbd>

if my hands are really tired i like to use:

1. <kbd>Alt</kbd>+<kbd>TAB</kbd>
1. wait 1 or 2 seconds (**no keyboard received**)  instead of pressing <kbd>Enter</kbd>
1. disable waiting if keyboard received

**Comment by DaveDavenport** [comment] 2020-10-10 20:18
duplicate of #1066 ?

**Comment by sl5net** [comment] 2020-10-10 21:07
nearly the same. Here waiting is disabled completely with first press

**Comment by sl5net** [comment] 2020-10-10 21:09
May set first window the last if those feature is chosen

**Comment by infiltratorXYZ** [comment] 2020-12-16 04:27
I have just written an implementation of this feature because I myself was looking for something similar.

I only have a problem with reading correctly the value that is set in the configuration file. I think the process of automatic entry acceptance itself works quite well.

As soon as I clean up the code and read the values from the configuration file, I will create PR.

**Comment by sl5net** [comment] 2020-12-16 09:03
> I have just written an implementation of this feature because I myself was looking for something similar.
> 
> I only have a problem with reading correctly the value that is set in the configuration file. I think the process of automatic entry acceptance itself works quite well.
> 
> As soon as I clean up the code and read the values from the configuration file, I will create PR.

sounds really useful :) :+1:

**Comment by DaveDavenport** [comment] 2022-01-25 10:26
Latest version allows you to set a timeout action (see manpage).

**Closed by DaveDavenport** 2022-01-25 10:26 UTC
Labels: Feature Request
