### ISSUE TITLE
[REQUEST] Verify theme or dry-run mode

### ISSUE THREAD

**Issue by aacebedo** [davatorium/rofi#1261] opened 2021-01-22 08:10 UTC
## Before creating a feature request

- [x] I checked the *next* branch to see if the feature has already been
  implemented

- [x] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?
I would like to be able to know if a theme is valid before really displaying rofi.

## How do you know that this problem exists today? Why is this important?
I can't know without actually starting rofi if a theme is valid.
I have a app that uses rofi as a simple menu system. I give control of the theming to the user but to have a consistent experience I need to validate the theme before executing rofi. I did not find any dry-run or quiet mode to do so.

## Who will benefit from it?
Any users of rofi wanting to avoid error messages about invalid theme or informing user of the error in a custom fashion.

## Version
Output of `rofi -v` :1.6.1

## Configuration
N/A

**Additional details:**
N/A

**Comment by DaveDavenport** [comment] 2021-01-22 08:11
duplicate of #1260

**Closed by DaveDavenport** 2021-01-22 08:11 UTC
Labels: Feature Request
