### ISSUE TITLE
parse-hosts option core dumped

### ISSUE THREAD

**Issue by deviantfero** [davatorium/rofi#984] opened 2019-06-28 07:59 UTC
## Version

1.5.3

## Configuration

[pastebin](https://pastebin.com/hL3sx69m)

## Launch Command

rofi -show run -parse-hosts

## Steps to reproduce

* enable host parsing
* try to use rofi

## What behaviour you see

* [1]    7531 segmentation fault (core dumped)  rofi -show run -parse-hosts

## What behaviour you expect to see

* normal rofi run

**Comment by DaveDavenport** [comment] 2019-06-28 08:01
duplicate of: #981, #980

**Closed by DaveDavenport** 2019-06-28 08:01 UTC

**Comment by DaveDavenport** [comment] 2019-06-28 08:07
Please update to 1.5.4, this release should have fixed the issue.
