### ISSUE TITLE
[BUG] Some lines not selectable with -async-pre-read 0

### ISSUE THREAD

**Issue by kaiec** [davatorium/rofi#1473] opened 2021-09-23 11:46 UTC
### Rofi version (rofi -v)

1.7.0

### Configuration

https://gist.github.com/kaiec/1c09fd974d436881a8b4005388a75483

### Launch command

cat rofi.txt | rofi -dmenu -i -async-pre-read 0

### Step to reproduce

When I use the -async-pre-read 0 workaround, sometimes lines are not selectable (Rofi 1.7.0, Arch, KDE):

[rofi.txt](https://github.com/davatorium/rofi/files/7217273/rofi.txt)

`cat rofi.txt | rofi -dmenu -i -async-pre-read 0`

Try to select the row starting with 44.

It works with an async-pre-read value of 1 or higher.

### Expected behavior

The line should be selected and written to stdout

### Actual behavior

No reaction, rofi keeps running

### Additional information

I added this as a comment to the by then still open issue #703 as there, -async-pre-read 0 is explicitly recommended as a workaround. I had the problem with freezes before I added the parameter, so this seems still to be an issue that somehow has to be adressed.

**Comment by DaveDavenport** [comment] 2021-09-23 13:03
I put a fix in git (could not reproduce original issue, but that is not too strange given the bug), can you test?

**Comment by kaiec** [comment] 2021-09-24 09:35
It works, ~~but today I could not reproduce the bug in the installed version, neither. This fits my experience, however, it seemed to affect random lines sometimes.~~ EDIT: I forgot the async-pre-read flag, I still can reproduce it on my machine, and indeed, with the git version, it seems to be fixed.

I am not too familiar with C, but if the uninitialized nonselectable flag basically means that it might be true or false depending on whatever was in memory, it certainly would fit the behaviour. OTOH, I wonder how this is connected to the async-pre-read flag, as add_read is used in both cases, or was it only coincidence that I thought a change of the flag would fix it?

Anyway, thanks, I keep my fingers crossed that this is fixed now and report back, should it ever happen again.

**Comment by DaveDavenport** [comment] 2021-09-24 09:57
yeah, it is uninitialized memory..  the behaviour is not predictable. Should be fixed with this.

**Closed as completed by DaveDavenport** 2021-09-24 09:57 UTC
Labels: bug
