### ISSUE TITLE
[BUG] rofi block mouse/keyboard

### ISSUE THREAD

**Issue by nbeliy** [davatorium/rofi#1063] opened 2020-03-02 23:29 UTC
## Version

Version: 1.5.0

## Configuration

[`rofi -help`](https://gist.github.com/nbeliy/abf09426c520619c7aa2f0cac9a1c2db.js)

## Launch Command

`rofi -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font 'Noto Sans 10'`

## Steps to reproduce

- Mount an external drive using mount menu
- Copy large data to this drive (large enought to `umount` take some time )
- Unmount drive using umount rofi mods

## What behaviour you see

- rofi blocks any keyboard input removing any way to communicate with PC until umount command is finished

## What behaviour you expect to see

- keyboard not blocked, allowing usage of non-rofi window

**Additional details:**
- [config file](https://gist.github.com/nbeliy/e0c654dfaa66524113025dbf392e8b0a.js)
- [mount script](https://gist.github.com/nbeliy/f483cd67ae7a0ca2ab16905369a7b866)
- [unmount script](https://gist.github.com/nbeliy/db762e7b60255b3b3afe19e1ec85f985)
- [awk parcing](https://gist.github.com/nbeliy/3bd3b120125f691723b6552e6d99f44e)

**Comment by DaveDavenport** [comment] 2020-03-03 16:54
duplicate of: #864 and info in #857

**Closed by DaveDavenport** 2020-03-03 16:54 UTC
Labels: Incomplete Report - Please follow the guidelines, bug
