### ISSUE TITLE
[BUG] rofi-git fails to build on Archlinux

### ISSUE THREAD

**Issue by devopsdeluxe** [davatorium/rofi#1106] opened 2020-04-25 22:56 UTC
My C is a tad rusty at the moment, but if pointed in the right direction, I would be happy to take a shot at fixing this.

EDIT: Introduced in commit: https://github.com/davatorium/rofi/commit/151547a99ed142168ec4a11e526102994f6736a9

## Steps to reproduce

This snippet assumes you're running Archlinux, and that [aur-utils](https://aur.archlinux.org/packages/aurutils/) is installed!

```sh
$ git clone https://aur.archlinux.org/rofi-git/
$ cd rofi-git
$ aur chroot
```
The output should be similar to [this](https://gist.github.com/devopsdeluxe/5aa5ca7b2b3ec9a949acf0fda735e848), with an error [here](https://gist.github.com/devopsdeluxe/5aa5ca7b2b3ec9a949acf0fda735e848#file-20200425_rofi-git_aur_chroot-log-L390)

## What behaviour you see

An [unsuccessful](https://gist.github.com/devopsdeluxe/5aa5ca7b2b3ec9a949acf0fda735e848#file-20200425_rofi-git_aur_chroot-log-L390) build

## What behaviour you expect to see

A successful build.

**Additional details:**

* AUR Links:
  * https://aur.archlinux.org/packages/rofi-git/
  * https://aur.archlinux.org/cgit/aur.git/?h=rofi-git

**Comment by gardotd426** [comment] 2020-04-26 01:27
Can confirm.

**Comment by DaveDavenport** [comment] 2020-04-26 08:59
I don't maintain the aur package, please file the bug with them.
(librsvg seems to be missing)

**Comment by DaveDavenport** [comment] 2020-04-26 09:03
sorry, misread it completely.

**Comment by DaveDavenport** [comment] 2020-04-26 09:44
Should be fixed, please test.

**Comment by xircon** [comment] 2020-04-26 09:49
Confirmed working here.

**Comment by DaveDavenport** [comment] 2020-04-26 09:52
Thanks.

**Closed by DaveDavenport** 2020-04-26 09:52 UTC
Labels: bug
