### ISSUE TITLE
[BUG] Closing windows on windowcd makes windows from all workspaces visible

### ISSUE THREAD

**Issue by hyeoniuwu** [davatorium/rofi#2046] opened 2024-11-03 17:46 UTC
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/hyeoniuwu/7a1f2c9cca54e418ef08eb99f93c861a#file-config-rasi

### Theme

https://gist.github.com/hyeoniuwu/7a1f2c9cca54e418ef08eb99f93c861a#file-theme-rasi

### Timing report

https://gist.github.com/hyeoniuwu/7a1f2c9cca54e418ef08eb99f93c861a#file-timing_report

### Launch command

rofi -show windowcd -modes windowcd

### Step to reproduce

1. Have close-on-delete: false; for windowcd
2. Have windows on more than one desktop.
3. Use the launch command (rofi -show windowcd -modes windowcd), and close one of the windows in windowcd.

### Expected behavior

After closing one of the windows in the current desktop, that window should be destroyed, while all others intact.

### Actual behavior

Upon closing one window in the current desktop, all other windows from all desktops become visible.

### Additional information

Reproduced on Xfce and i3.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment] 2024-12-25 18:40
I cannot reproduce this.  It works fine on i3.
What window manager are you using? 

edit: missed you mention i3/xfce.   what version do you use? do you have multimonitor setup?

**Comment by DaveDavenport** [comment] 2024-12-26 13:43
From your report I thought you said the windows become visible (on the workspace). This I was looking for, do you mean they become visible in rofi?  This should have been fixed in c82754307 .

If it is not this, please let me know.

**Closed as completed by DaveDavenport** 2024-12-26 13:43 UTC
Labels: bug
