### ISSUE TITLE
[BUG] Can't run shell commands in drun mode

### ISSUE THREAD

**Issue by Myvillithdar** [davatorium/rofi#1187] opened 2020-09-10 22:28 UTC
## Version

Output of `rofi -v`
`Version: 1.6.0`

## Configuration

output of `rofi -help`:
https://gist.github.com/Myvillithdar/3f2a4666ef96b350092c9c2992577960

my config file:
https://gitlab.com/Myvillithdar/i3config/-/blob/master/base-files/config.rasi

## Launch Command

`rofi -show drun`

## Steps to reproduce

- Type `reboot`
- Press enter

## What behaviour you see

- Nothing happens

## What behaviour you expect to see

-  Before 1.6.0, my computer would reboot (b/c `reboot` doesn't match any desktop files, rofi would run `reboot` from `/usr/bin/`, basically falling back to `run` mode behavior.)

**Additional details:**

Under "drun", the manpage says:
> Pressing the accept-custom binding (control-enter or shift-enter) with custom input (no entry matching) will run the command in a terminal.

...but control-enter and shift-enter also don't do anything.

I see that the changelog for 1.6.0 includes:
> [DRun] Don't run custom commands.

I'm not entirely sure if this is what that refers to, so maybe this was an intentional change, but in any case I'd expect control-enter or shift-enter to still run the command since that's what the manpage says.  If this was an intentional change, then it would be nice to have a config option to restore the old behavior.

**Comment by mkhan45** [comment] 2020-09-11 00:34
>  If this was an intentional change, then it would be nice to have a config option to restore the old behavior.
I agree; it's kind of essential to my workflow. 

Regardless, the man page claims that pressing the accept-custom binding will run a custom command and that's not the case right now.

**Comment by DaveDavenport** [comment] 2020-09-11 07:36
Original issue: #966

**Comment by mkhan45** [comment] 2020-09-11 16:48
Do you intend to restore the previous behavior in any way or should I fork the repo and be out of your way?

**Comment by DaveDavenport** [comment] 2020-09-11 16:54
please fork the repo.

**Comment by bruno-unna** [comment] 2020-09-11 17:03
@mkhan45 Just to understand the issue, what is wrong with using the "run" mode in addition to "drun"?

**Comment by mkhan45** [comment] 2020-09-11 17:19
> @mkhan45 Just to understand the issue, what is wrong with using the "run" mode in addition to "drun"?

Mostly because I don't want to have to use different keybindings for starting programs and running commands, but also because I don't want to have to press ctrl+enter instead of enter to run a shell command. Additionally, I'd never use the `run` mode for a purpose other than running shell commands, so it's just more convenient to have it packed into `drun`.

**Comment by Myvillithdar** [comment] 2020-09-11 17:45
Hmmm, I definitely see the point in #966 -- that error message after a typo is inconvenient to deal with.  In my mind the ideal solution would be to add a config option for drun mode that runs the input as a shell command if the list is empty _and_ if a matching command exists in $PATH, and does nothing otherwise.

I suppose as a workaround, I could simply create desktop entries for `shutdown` and `reboot`, and that would be enough to largely fix my own workflow (though I can't speak for anyone else).  I've always appreciated the convenience of being able to invoke arbitrary commands from drun mode, but at the moment I can't think of any other commands that I regularly do that with.

**Comment by DaveDavenport** [comment] 2020-09-11 19:26
The problem is a bit that there is no one solution to please everybody, but you cannot add 1001+ options either.
I myself use combi mode to combine window/drun/run, for me that avoids the need to run custom commands. If I still need to, I can do `!r command` to run an custom command.

**Comment by DaveDavenport** [comment] 2020-09-11 19:44
I guess we need to come up with some solution, (beside forking)

**Comment by DaveDavenport** [comment] 2020-09-11 19:52
I kinda like the idea of returning to the list on error. @dannycolin would that work for you?

**Comment by dannycolin** [comment] 2020-09-11 20:06
> I kinda like the idea of returning to the list on error. @dannycolin would that work for you?

Yes. It would.

**Comment by DaveDavenport** [comment] 2020-09-13 14:44
A quick test, seems that I had a lot of infra already there :smile: 
```patch
diff --git a/source/dialogs/drun.c b/source/dialogs/drun.c
index aac7a934..94200cbc 100644
--- a/source/dialogs/drun.c
+++ b/source/dialogs/drun.c
@@ -1041,7 +1041,12 @@ static ModeMode drun_mode_result ( Mode *sw, int mretv, char **input, unsigned i
         }
     }
     else if ( ( mretv & MENU_CUSTOM_INPUT ) && *input != NULL && *input[0] != '\0' ) {
-        retv = RELOAD_DIALOG;
+        RofiHelperExecuteContext context = { .name = NULL };
+        gboolean             run_in_term = ( ( mretv & MENU_CUSTOM_ACTION ) == MENU_CUSTOM_ACTION );
+        // FIXME: We assume startup notification in terminals, not in others
+        if ( ! helper_execute_command ( NULL, *input, run_in_term, run_in_term ? &context : NULL ) ) {
+            retv = RELOAD_DIALOG;
+        }
     }
     else if ( ( mretv & MENU_ENTRY_DELETE ) && selected_line < rmpd->cmd_list_length ) {
         // Possitive sort index means it is in history.
diff --git a/source/rofi.c b/source/rofi.c
index 314ea097..88132977 100644
--- a/source/rofi.c
+++ b/source/rofi.c
@@ -208,7 +208,7 @@ static void run_switcher ( ModeMode mode )
 void process_result ( RofiViewState *state )
 {
     Mode *sw = state->sw;
-    rofi_view_set_active ( NULL );
+ //   rofi_view_set_active ( NULL );
     if ( sw != NULL ) {
         unsigned int selected_line = rofi_view_get_selected_line ( state );;
         MenuReturn   mretv         = rofi_view_get_return_value ( state );
@@ -246,12 +246,17 @@ void process_result ( RofiViewState *state )
              * Load in the new mode.
              */
             rofi_view_switch_mode ( state, modi[mode] );
-            rofi_view_set_active ( state );
             curr_switcher = mode;
             return;
+        } else {
+          // On exit, free current view, and pop to one above.
+          rofi_view_free ( state );
+          rofi_view_set_active ( NULL );
+          return;
         }
     }
     rofi_view_free ( state );
+          rofi_view_set_active ( NULL );
 }
 
 /**
```

**Comment by DaveDavenport** [comment] 2020-09-13 15:12
Added branch with patch.

**Comment by DaveDavenport** [comment] 2020-09-13 19:56
merged in changes. please test.

**Comment by dannycolin** [comment] 2020-09-13 20:47
> merged in changes. please test.

Works perfectly! One small thing. Maybe we could add a "Press Enter to return to Rofi" in the error message. I built my muscle memory to press ESC, Super + a to quickly reopen a fresh instance of Rofi and I'm guessing I'm not the only one :). The message would help the user discover that new feature. 

Also, is there a technical limitation or other reason not to show the message in the same window as Rofi since there's already a widget to show messages? It could prevent disrupting the UX because the user would be able to edit the input content right away.

**Comment by DaveDavenport** [comment] 2020-09-13 21:01
> Also, is there a technical limitation or other reason not to show the message in the same window as Rofi since there's already a widget to show messages? It could prevent disrupting the UX because the user would be able to edit the input content right away.

This implementation was already there,  I just fixed the calling off it.  One reason not to use the message widget is that it might already be used/set/reset by the mode.

**Comment by mkhan45** [comment] 2020-09-14 01:17
> merged in changes. please test.

It works great for me. Thanks!

**Comment by DaveDavenport** [comment] 2020-09-14 07:35
> > merged in changes. please test.
> 
> It works great for me. Thanks!

**Closed by DaveDavenport** 2020-09-14 07:35 UTC
Labels: bug
