### ISSUE TITLE
[BUG] Icons in script mode takes a small delay before rendering

### ISSUE THREAD

**Issue by kriansa** [davatorium/rofi#1668] opened 2022-08-02 02:48 UTC
### Rofi version (rofi -v)

Version: 1.7.3-123-g8e8765e2

### Configuration

[Default one, or `-no-config`](https://gist.github.com/kriansa/25e63fa6ceebb1ff6f86ba701b299241)

### Launch command

`rofi -modi myscript:./script.sh -show myscript -show-icons`

### Step to reproduce

* Ensure you have Adwaita gtk theme installed (for the icons)
* Place the following content into a file named `script.sh` and make it executable:
    ```sh
    #!/usr/bin/env bash
    svg=/usr/share/icons/Adwaita/scalable/actions/media-playback-start-symbolic.svg
    png=/usr/share/icons/Adwaita/16x16/ui/checkbox-checked-symbolic.symbolic.png
    echo -e "Option 1\0icon\x1f$png"
    echo -e "Option 2\0icon\x1f$png"
    echo -e "Option 3\0icon\x1f$svg"
    echo -e "Option 4\0icon\x1f$svg"
    ```
* Run: `rofi -modi myscript:./script.sh -show myscript -show-icons`

### Expected behavior

I see both the text (Option 1, Option 2...) and the icons showing up at the same time

### Actual behavior

I see a small delay before the icons are displayed. You can re-run the command several times and you will notice that.

### Additional information

Oddly enough, this seems to be caused by the rendering of SVGs. If you replace in the two last lines of the script, `$svg` by `$png` and re-run the script, you will see it rendering instantly, but if there's at least one SVG in the list then that delay starts showing up.

**Comment by kriansa** [comment] 2022-08-02 13:37
Hi @DaveDavenport, I noticed this issue was tagged as incomplete request, I apologize for that mistake. If it was because no config was provided, it was because none is needed and the default one (or `-no-config`) is sufficient to reproduce the issue.

Nonetheless I have provided the one being used (the default one). Let me know if this is still incomplete.

**Comment by DaveDavenport** [comment] 2022-08-02 13:48
The issue template very explicitly asks to provide information, it does this for a good reason.  So if not provided it will get marked as 'incomplete'. I am not sure how I can make this more clear in the template. I try to be consistent in enforcing this.


Anyway this is not a bug but intended behavior. Loading icons is slow (lookup an  icon possibly via icon-theme, rendering it (svg is in general slow-ish), scaling etc.). Especially with SVG rendering an icon depends on the SVG complexity and can take extremely long. You noticed this yourself in your issue. (that png is near instant, svg slower).

Therefor rofi loads the text directly, icons are done via a threading pool in the background and the view is reloaded once an icon is rendered onto a surface and can be displayed. Making  it wait till icon loading is done before displaying will be very annoyingly slow.

**Closed as completed by DaveDavenport** 2022-08-02 13:48 UTC
Labels: bug, Incomplete Report - Please follow the guidelines

**Comment by kriansa** [comment] 2022-08-02 15:41
Thanks for the details. It is indeed a very minor annoyance, I just find it weird that I don't see that issue when I run `rofi -no-config -show drun -show-icons -icon-theme Papirus`, where all icons are SVGs.

> The issue template very explicitly asks to provide information, it does this for a good reason. So if not provided it will get marked as 'incomplete'. I am not sure how I can make this more clear in the template. I try to be consistent in enforcing this.

Don't worry about that, the template is good enough already. It's just that I tried to make the reproduction steps as minimal as possible, so I omitted that in an attempt to save time, that's my bad.

**Comment by DaveDavenport** [comment] 2022-08-02 15:43
> Thanks for the details. It is indeed a very minor annoyance, I just find it weird that I don't see that issue when I run rofi -no-config > -show drun -show-icons -icon-theme Papirus, where all icons are SVGs.

And that is exactly why it is async, you never know before hand how long it takes to load.

**Comment by kriansa** [comment] 2022-08-02 15:47
I see, but the delay is consistent on one command (`script mode`) while inexistent on the other (`drun mode`), when both are loading the exact same icon size and format (SVG).

**Comment by DaveDavenport** [comment] 2022-08-02 15:54
both of them use `rofi_icon_fetcher_query`, 
https://github.com/davatorium/rofi/blob/next/source/modes/drun.c#L1332
and
https://github.com/davatorium/rofi/blob/next/source/modes/script.c#L446

So I cannot directly explain it.  (papirus does ship different sizes svg, the 'icon-theme' way will pick the closest size one. I assume smaller icons are also less detailed?  are you passing the same size?)
