### ISSUE TITLE
[BUG] Can't detach / fork using ampersand (&) syntax in user scripts

### ISSUE THREAD

**Issue by scrouthtv** [davatorium/rofi#1206] opened 2020-10-03 16:40 UTC
## Version
`Version: 1.6.0`

## Configuration
https://gist.github.com/scrouthtv/b7ad1158ecb7af2ef1957e4d79ce36a6

## Launch Command
` ~ rofi`

## Steps to reproduce

- Step 1: Paste the following into `~/git/rofi-scripts/emoji4rofi.sh.old`
```
#!/bin/bash

if [[ -z "$@" ]]; then
	echo a
	echo b
	echo c
	echo d
else
	# xdotool type --clearmodifiers "$@" doesn't work because rofi still has focus at this point
	(sleep 1s; xdotool type --clearmodifiers "$emo") &!
fi
```
- Step 2: Open a program that can accept text (vim, browser, notepad, etc) and open rofi
- Step 3: Select anything from the emoji category

## What behaviour you see

- nothing happens for 1 second
- text isn't inserted anywhere

## What behaviour you expect to see

- rofi closes instantly as the part in parantheses beginning with `sleep 1s` is forked to a new process and detached
- text is inserted in the program that can accept text after 1 second

**Comment by DaveDavenport** [comment] 2020-10-04 11:45
Duplicate of: #1077, #1063, #864 and info in #857

**Closed by DaveDavenport** 2020-10-04 11:45 UTC
Labels: bug
