### ISSUE TITLE
No focus and no input possible on Fedora, Gnome, Wayland

### ISSUE THREAD

**Issue by wazum** [davatorium/rofi#991] opened 2019-07-07 15:00 UTC
## Version

Version: 1.5.2

## Configuration

https://gist.github.com/wazum/512d59800644cc486625542276de7136

## Launch Command

rofi -show window

## Steps to reproduce

Fedora 30, Gnome, Wayland (WaylandEnable=true)

Open a terminal (tested with default Terminal or Terminator)

Start rofi (via command line or shortcut)

## What behaviour you see

Can't focus the rofi window,
when I type text it appears in the terminal, not in the rofi window

## What behaviour you expect to see

Focus is on rofi window, when I type text it appears in rofi window

**Comment by sardemff7** [comment] 2019-07-07 15:03
Duplicate of #446. Nothing we can do about it, especially on GNOME. Sorry.

**Closed by sardemff7** 2019-07-07 15:03 UTC
