### ISSUE TITLE
[BUG] `-lines` option doesn't work as excepted

### ISSUE THREAD

**Issue by k4leg** [davatorium/rofi#1488] opened 2021-09-30 21:19 UTC
### Rofi version (rofi -v)

1.7.0

### Configuration

http://0x0.st/-gXw.txt

### Launch command

`rofi -lines 4 -dmenu -p 'power menu'`

### Step to reproduce

* For example, get [this](https://raw.githubusercontent.com/k4leg/dotfiles/a723d28323fc7536e214a8fe5c46727d6e257bed/dot_local/bin/executable_rofi-power-menu) script.
* Try run this script.
* See the bug.
* `sed -i 's/-lines/-l/' executable_rofi-power-menu`.
* See the no bug.

### Expected behavior

4 lines instead default value in this case.

### Actual behavior

Default value instead 4 lines in this case.

### Additional information

On 1.6.1 it works correctly.

**Comment by DaveDavenport** [comment] 2021-09-30 22:00
Duplicate of: https://github.com/davatorium/rofi/issues/1446
See: 
https://github.com/davatorium/rofi/discussions/1447
https://github.com/davatorium/rofi/discussions/1407

Please read the guidelines, the sticky, etc. 
Relevant [manpage](https://github.com/davatorium/rofi/blob/next/doc/rofi.1.markdown#dmenu-specific)

**Closed as completed by DaveDavenport** 2021-09-30 22:00 UTC
Labels: bug
