### ISSUE TITLE
Weird issues in displaying workspace names when workspaces named with unicode icons

### ISSUE THREAD

**Issue by sicklybeans** [davatorium/rofi#977] opened 2019-06-05 21:22 UTC
## Version

    $ rofi -v
    Version: 1.5.2

## Configuration
https://gist.github.com/sicklybeans/b168b0451992a6943200e5511d0bca72

## Launch Command

    $ rofi -show window

## Steps to reproduce

This is all within `i3`. Not sure if it can be reproduced in other DEs with workspaces. It happened to me while using FontAwesome, but the strange behavior suggests that it is a `rofi` bug, not a FontAwesome bug. Please correct me if I'm wrong.

* Make an ordinary workspace in i3, here mine is named "1" and contains a terminal with the window title "weirdly named workspace". Launch rofi via `rofi -show window` and everything looks fine
![fig1_ws_1](https://user-images.githubusercontent.com/4105559/58989929-d9d42c00-87b2-11e9-8d3f-159dcea381de.png)

* Now rename workspace "1" to the FontAwesome envelope unicode character (\uf0e0) and launch rofi again. Rofi shows displays the workspace name as the FontAwesome envelope icon followed by a series of missing unicode symbols:
    `$ i3-msg 'rename workspace 1 to '`
    `$ rofi -show window`
![fig2_ws_envelope](https://user-images.githubusercontent.com/4105559/58990250-7991ba00-87b3-11e9-896e-2979081d5ce7.png)

* Here's where things get weirder. Rename the envelope workspace to the same envelope character followed by any ordinary alphanumeric character, like "a" and launch rofi again. Rofi displays the workspace name exactly as you would expect without any bugs
    `$ i3-msg 'rename workspace  to a'`
    `$ rofi -show window`
![fig3_ws_envelope_a](https://user-images.githubusercontent.com/4105559/58990501-0472b480-87b4-11e9-8a2f-52303f37f1b0.png)

* Finally, if you rename the workspace again to the FontAwesome gamepad unicode symbol, rofi behaves completely normally. The bug that occurs with the envelope does not happen.
    `$ i3-msg 'rename workspace a to '`
    `$ rofi -show window`
![fig4_ws_controller](https://user-images.githubusercontent.com/4105559/58990569-34ba5300-87b4-11e9-872c-65a026181fbf.png)

**Additional Notes**
 * I haven't tested other FontAwesome icons. 
 * The order of these steps doesn't matter. Any workspace with those names behaves like that
 * A possible useful clue: If you rename the workspace to " a" (the envelope glyph followed by a space followed by a character, rofi displays it correctly except with a missing unicode symbol instead of the space.
 * While making screenshots for this, I also noticed rofi sometimes labels windows with the incorrect workspace. I haven't figured out exactly what triggers this or if it is related to the use of icons in my workspace names. I will file a separate bug report for that problem.

## What behaviour you see

I name a workspace with the single FontAwesome icon "\uf0e0" (envelope). When I launch `rofi -show window`, the workspace name displays as the envelope icon followed by a series of missing unicode glyphs

* -

## What behaviour you expect to see

I expect that when I launch `rofi -show window`, the workspace name is the correctly rendered FontAwesome icon without any trailing glyphs

* -

**Comment by sicklybeans** [comment] 2019-06-05 21:23
Apologies if this turns out to be a FontAwesome issue

**Comment by DaveDavenport** [comment] 2019-06-05 22:41
Can you paste the output of:

```
 xprop -root _NET_DESKTOP_NAMES
```

thx.

**Comment by sicklybeans** [comment] 2019-06-06 13:01
https://gist.github.com/sicklybeans/21006f9f87dda716fd819ef87df11b1a

**Comment by DaveDavenport** [comment] 2019-06-07 11:09
I don't see any unicode icons in the desktop names.

**Comment by sicklybeans** [comment] 2019-06-07 11:12
Oh sorry I didn't do it while the desktop names had the buggy symbols (I stopped using those symbols). Here's a version with the bug: https://gist.github.com/sicklybeans/32b4aade22546516f46193c2dce9a91f

**Comment by DaveDavenport** [comment] 2019-06-07 11:16
thx

**Comment by DaveDavenport** [comment] 2019-06-07 11:29
I cannot reproduce the issue. I nicely see just the envelope icon on step 2.

![image](https://user-images.githubusercontent.com/406245/59101048-255c1680-8928-11e9-83c4-e10e3e16312b.png)

What i3 version do you run?

**Comment by sicklybeans** [comment] 2019-06-07 16:35
4.16.1

**Comment by demaisj** [comment] 2019-06-13 22:16
Hi,

I have a similar problem using material design icons on a dmenu script. The space is rendered as an unknown character code U+0020 directly after some icons.

Icons showing the bug:
- U+F425  (Private Use Area)
- U+F708  (Private Use Area)
- U+F343  (Private Use Area)
- U+F150  (Private Use Area)

Icons not showing the bug:
- U+F903 賈 (CJK Compatibility Ideographs)

It seems to me that the bug only occurs when the icon is in the Private Use Area unicode block, used by the majority of the icon fonts.

![rofi-2019-06-14-0013-00000](https://user-images.githubusercontent.com/2797696/59470812-3b426d80-8e39-11e9-9a64-7de0c395ba7a.png)

Script:
```bash
#!/bin/bash

OPTIONS=" Poweroff Action
賈 Sleep Action
 Restart Action
 Logout Action
 Hibernate Action
a Hibernate Action2"

rofi <<<$OPTIONS -dmenu -no-config -font "sans-serif 11"
```

Font configuration:
```
> fc-match -s "sans-serif"
NotoSans-Regular.ttf: "Noto Sans" "Regular"
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
materialdesignicons-webfont.ttf: "Material Design Icons" "Regular"
[...]
```

OS: 
- Arch Linux

Packages:
- rofi 1.5.2-1
- rofi-dmenu 1-1
- ttf-material-design-icons-webfont 3.6.95-1
- noto-fonts 20190111-1
- noto-fonts-cjk 20190409-1
- noto-fonts-emoji 20180810-2
- noto-fonts-extra 20190111-1

**Comment by DaveDavenport** [comment] 2019-06-14 07:42
Given pango is used to do font rendering. Does it work correct in other pango applications (like gedit)?

@sicklybeans are you using archlinux?

**Comment by demaisj** [comment] 2019-06-14 08:45
I've checked, it does not work in gedit:
![image](https://user-images.githubusercontent.com/2797696/59496132-17127b00-8e91-11e9-9eea-559d78ae0f54.png)

**Comment by sicklybeans** [comment] 2019-06-20 11:11
@DaveDavenport I'm using Manjaro. If it's a pango issue then it looks like we are stuck : (

**Comment by demaisj** [comment] 2019-07-29 15:12
This is now fixed for me:
![rofi-2019-07-29-1710-00000](https://user-images.githubusercontent.com/2797696/62059594-e1003f00-b223-11e9-91f8-cd6bb415069e.png)

Package versions:
- rofi 1.5.4-1
- pango 1:1.44-1
- fontconfig 2:2.13.1+12+g5f5ec56-1

**Comment by DaveDavenport** [comment] 2019-07-29 15:47
There was  a pango update?

**Comment by demaisj** [comment] 2019-07-29 15:54
Yes, I forgot to clarify it.

**Comment by DaveDavenport** [comment] 2019-07-29 15:56
Thanks.  Hopefully that means this issue can be closed!.

**Comment by DaveDavenport** [comment] 2019-08-09 18:01
no more reports. so assume it is fixed upstream.

**Closed by DaveDavenport** 2019-08-09 18:01 UTC
Labels: Bug in used library
