### ISSUE TITLE
[BUG] Rofi can't show icons of desktop entries when the desktop entry contains a path for the icon

### ISSUE THREAD

**Issue by Samueru-sama** [davatorium/rofi#1977] opened 2024-04-17 21:15 UTC
### Rofi version (rofi -v)

Version: 1.7.5 (Also happens with rofi-git).

### Configuration

https://gist.github.com/Samueru-sama/7fa680f9a3485756aef1141e2fcacee4

### Theme

https://gist.github.com/Samueru-sama/4b1976c1abdccd4e469599922184ba3f

### Launch command

rofi -show-icons -show drun

### Step to reproduce

This issue happens when the .desktop file contains a path to an icon in `/opt`. It doesn't happen if the icon is in $HOME oddly enough. 

![image](https://github.com/davatorium/rofi/assets/36420837/456b3d0c-39dc-4cc3-aa8b-e08d4eb39bf4)

This issue also only happens with rofi, as other application launchers like the whisker menu for the xfce4-panel don't have this issue, neither thunar has the issue. 

![image](https://github.com/davatorium/rofi/assets/36420837/8db05220-deed-42d7-90ca-3bdb31534b73)

### Expected behavior

The icon should just display like it does when the `Icon=` path in the desktop file points to home instead. 

### Actual behavior

Icon doesn't display. 

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment] 2024-04-18 19:52
Can you pastebin a desktop file?

**Comment by DaveDavenport** [comment] 2024-04-18 19:55
Rofi does 'g_path_is_absolute' on the icon passed to load (before it queries the icon theme), and loads it directly if that returns true.
So I wonder why it fails.

**Comment by Samueru-sama** [comment] 2024-04-18 20:02
> Can you pastebin a desktop file?

```
[Desktop Entry]
Version=1.0
Exec=es-de
Icon=/opt/es-de/icons/es-de
Terminal=false
Type=Application
StartupNotify=true
Hidden=false
Categories=Game;Emulator;
Name=ES-DE
GenericName=Emulator Frontend
Keywords=emulator;emulation;front-end;frontend;
```

If I change the path in the icon for any random image in my $HOME the issue gets fixed, it is when the `Icon=` path points to /opt that it can't display it.

**Comment by DaveDavenport** [comment] 2024-04-18 20:05
Is this an image?  rofi looks for valid file extension (maybe not in this case, but this looks odd):

> Icon=/opt/es-de/icons/es-de

**Comment by Samueru-sama** [comment] 2024-04-18 20:11
> Is this an image? rofi looks for valid file extension:
> 
> > Icon=/opt/es-de/icons/es-de

Yes it is an image, however it doesn't have the `.png` extension. 

![image](https://github.com/davatorium/rofi/assets/36420837/053aca24-7ef8-4461-9ac7-cbe35b75c927)

I just tested adding the .png to the image and it didn't work. 

![image](https://github.com/davatorium/rofi/assets/36420837/e718b9d5-f306-477f-bf44-0e01682ef808)

**Comment by DaveDavenport** [comment] 2024-04-18 20:12
weird..  it does a `gdk_pixbuf_new_from_file_at_scale` on the path.. can you attach the image?

(if you add .png, did you also update the desktop file?)

I cannot find this file in the appimage..

**Comment by Samueru-sama** [comment] 2024-04-18 20:21
> weird.. it does a `gdk_pixbuf_new_from_file_at_scale` on the path.. can you attach the image?
> 
> (if you add .png, did you also update the desktop file?)

It isn't just this image, it is any image from any application installed in that location. And even more weird, if I move the image to my home and change the path it suddenly works: 

![image](https://github.com/davatorium/rofi/assets/36420837/cd0bdec2-c6cf-428e-84f1-0b7fe1b74ba5)
![image](https://github.com/davatorium/rofi/assets/36420837/b769f741-6db1-4916-93b6-4d874de4980d)


>I cannot find this file in the appimage..

es-de was installed with AM, this: https://github.com/ivan-hc/AM It often pulls the icon from the repo or other sites.

You can quickly test this by doing an `am -i es-de` or any other application. 

AM has a portable mode called appman where the appimages and icon get installed in home instead of /opt, when that is used then rofi has no issue displaying the icons in the .desktop path, only when it is in /opt it is that this happens.

**Comment by DaveDavenport** [comment] 2024-04-18 20:23
Can't you just attach the image?  I don't want to install weird tools just to test?

**Comment by DaveDavenport** [comment] 2024-04-18 20:23
Looking at the code, no extension it is not loaded.
There is no code in rofi that should not load from /opt.

**Comment by DaveDavenport** [comment] 2024-04-18 20:25
Converting the svg to png myself:
![rofi-2024-04-18-2224-00000](https://github.com/davatorium/rofi/assets/406245/73822329-93b7-451f-85d6-194cf1393ae9)

Putting it in /opt/es-de/ etc   with the png extension and adding .png in desktop file and it loads fine.

>(process:19050): Helpers.IconFetcher-DEBUG: 22:24:33.241: Query: /opt/es-de/icons/es-de.png(85)
(process:19050): Helpers.IconFetcher-DEBUG: 22:24:33.241: Found path: /opt/es-de/icons/es-de.png
(process:19050): Helpers.IconFetcher-DEBUG: 22:24:33.250: Got surface from pixbuf: /opt/es-de/icons/es-de.png

**Comment by DaveDavenport** [comment] 2024-04-18 20:28
I suspect this is the issue: https://github.com/davatorium/rofi/blob/next/source/rofi-icon-fetcher.c#L357
and it will work when setting a correct extension.

**Comment by Samueru-sama** [comment] 2024-04-18 20:28
> Can't you just attach the image? I don't want to install weird tools just to test?

![es-de](https://github.com/davatorium/rofi/assets/36420837/1edb8531-3331-4672-aa6f-7734cb639056)

Once again the issue isn't with the image, happens with all other apps in that location: 

![image](https://github.com/davatorium/rofi/assets/36420837/fc9e54fc-6c86-40d4-bbf4-17e4e178cb4a)

And if I go and move the librewolf icon from /opt, place it in home and edit the .desktop file to change the path of the icon to point to home it works.

**Comment by DaveDavenport** [comment] 2024-04-18 20:30
I do not think it is the location. I have many things in my /opt that show up just fine.

If it is an absolute path, there is no code that checks 'location'.. there is code that checks for a  extension.
I think that code is wrong,  you can test that by renaming a file to have a .png and update the .desktop file to poin the file with the .png extension. 

You said you did this, so I want to double check the file, to check that we are not hunting two different bugs.

**Comment by DaveDavenport** [comment] 2024-04-18 20:33
Or try latest git, where I removed that check.

**Comment by DaveDavenport** [comment] 2024-04-18 20:44
https://github.com/davatorium/rofi/blob/next/source/rofi-icon-fetcher.c#L302 <-- here we check absolute path.
https://github.com/davatorium/rofi/blob/next/source/rofi-icon-fetcher.c#L303 <-- here we set icon_path to this path.
https://github.com/davatorium/rofi/blob/next/source/rofi-icon-fetcher.c#L368 <-- here we load the image.
No path check .

(It worked in  your homedir because it check for extension is broken and it checks for a '.').

**Comment by DaveDavenport** [comment] 2024-04-18 20:47
Fixed in: 9b6e70b365116935158413034cf2aeb16affd9d4

**Closed as completed by DaveDavenport** 2024-04-18 20:47 UTC
Labels: bug

**Comment by Samueru-sama** [comment] 2024-04-18 20:50
> Also happens with rofi-gi

I did try rofi-git as well (mentioned in the first comment of the issue).

Here is a video showing everything (and how it gets fixed when I move the icon to a different place in home): https://streamable.com/trhsno

But looks like I came too late, will update rofi-git again and update this.

**Comment by DaveDavenport** [comment] 2024-04-18 20:51
It works in home, as then it has a '.' in the file path ('/home/{user}/.local/').  This was a silly test (no idea why it was there).
This test is removed and should fix your issue.

**Comment by DaveDavenport** [comment] 2024-04-18 20:53
> I did try rofi-git as well (mentioned in the first comment of the issue).

I've updated git, that is why I suggested that.

**Comment by Samueru-sama** [comment] 2024-04-18 20:55
> > I did try rofi-git as well (mentioned in the first comment of the issue).
> 
> I've updated git, that is why I suggested that.

Alright I don't know if I need to wait for the rofi-git aur package to update, because I just reinstalled it and the issue of the video is still there. (Will reboot right now just in case that is needed).

**Comment by DaveDavenport** [comment] 2024-04-18 20:56
No reboot needed. 
I reproduced the issue you had with the above desktop file and image.. then it indeed did not work for me
after this commit it works for me.

**Comment by DaveDavenport** [comment] 2024-04-18 20:57
can you pastebin the output of rofi -v to check if you are indeed on latest.

**Comment by Samueru-sama** [comment] 2024-04-18 20:59
> No reboot needed. I reproduced the issue you had with the above desktop file and image.. then it indeed did not work for me after this commit it works for me.

It woks now, I had to reboot for some reason though. Thank you!

EDIT: Likely rofi didnt fully quit as I use it for other stuff in my system.

**Comment by DaveDavenport** [comment] 2024-04-18 21:00
>It woks now, I had to reboot for some reason though. Thank you!

Happy to hear it works.
Not sure why you need to reboot archlinux , rofi does not keep running, so every launch should be a new instance.
