### ISSUE TITLE
[BUG] Changing icon size on the fly

### ISSUE THREAD

**Issue by dionisisNik** [davatorium/rofi#1218] opened 2020-11-08 14:20 UTC
## Version

Output of `rofi -v`

Version: 1.6.0-23-g58a51f7f (makepkg)

## Configuration

[Output of `rofi -help`](https://gist.github.com/dionisisNik/ea416789eb72f3a49c5ca083a6310550)

## Launch Command

Alt+D with i3wm:
`rofi -show drun -modi drun -hide-scrollbar -width 20 -location 3 -show-icons -font "Scientifica 8" -matching fuzzy -drun-display-format {name}
`

## Steps to reproduce

- Set icons on on rofi launcher
- Set size of icons in rofi 
- Set size of icons for selected entries (like in config)

## What behaviour you see

- Icon size stays as original

## What behaviour you expect to see

- Selected icon size changes when element is selected  

**Additional details:**

1. [Link to my rofi config](https://github.com/dionisisNik/dotfiles/blob/master/.config/rofi/FullscreenRofi.rasi)

2. The attribute:
 `
#element-icon.selected {
     size: 60; 
     background-color: #666666 
 }
`
is probably correct, when background-color: #666666 is used the background color for the selected icon (only) changes.
 
3. The screenshot:
![bug](https://user-images.githubusercontent.com/57800665/98467436-f5303b80-21dd-11eb-88f3-95a18941d240.png)

**Comment by DaveDavenport** [comment] 2020-11-08 15:40
This is not a bug, but intended behavior.  Elements in a list should be fixed size. 
Having dynamic sized elements in the list would make all the sizing/paging computation a lot more complex, less intuitive (elements will change position based on selection) and slow it down. 
I have no intention to support this.

**Closed by DaveDavenport** 2020-11-08 15:40 UTC
Labels: bug
