### ISSUE TITLE
[BUG] In Window Managers, Attempting to close rofi results in loss of Xinput focus.

### ISSUE THREAD

**Issue by ryeenii** [davatorium/rofi#1233] opened 2020-12-09 03:57 UTC
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`
Version: 1.6.1-3-g1c9d975d (next)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
https://gist.github.com/ryeenii/c95e74315bba73ba33498db1bd034004

## Launch Command

`The commandline used to launch **rofi**`
`rofi -show drun` (or any other show mode).

## Steps to reproduce

1. Open rofi using a window manager binding
2. Attempt to close it by pressing Escape or Right Clicking.

## What behaviour you see

- X Keyboard Input should stop working *unless* you successfully spawn a window, instead of closing the menu instance. You are still able to use your mouse normally.
- This seems to have happened as soon as the Focus steal in override redirect commit was pushed (1c9d975).

## What behaviour you expect to see

- Regular Input.

**Additional details:**
- My configs are currently at [ryeenii/dotnii-rofi](https://github.com/ryeenii/dotnii-rofi).
- Demonstration (using xev): https://streamable.com/b8e7ye
- This is a litte more in-depth bug report to #1228 .

**Comment by DaveDavenport** [comment] 2020-12-09 06:43
duplicate of #1228

**Closed by DaveDavenport** 2020-12-09 06:43 UTC
Labels: bug
