### ISSUE TITLE
[BUG] Desktop Entry With Spaces Doesn't Work Properly

### ISSUE THREAD

**Issue by sethierophant** [davatorium/rofi#1244] opened 2020-12-24 18:55 UTC
## Version

Output of `rofi -v`

    Version: 1.6.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)

 [Gist](https://gist.githubusercontent.com/sethierophant/6f0a43ec3b86303b92642cd82212e1d0/raw/f4e44e73ab26ccdebb7a2d029aecf61e43af58c9/gistfile1.txt)

## Launch Command

The commandline used to launch **rofi**

    rofi -show drun

## Steps to reproduce

- Add this desktop entry (for example) to `~/.local/share/applications/Sample.desktop`

```
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=FTL: Advanced Edition
GenericName=FTL: Advanced Edition
Comment=FTL: Advanced Edition
Icon=/home/set/Downloads/Games/FTL Advanced Edition/support/icon.png
Exec="/home/set/Downloads/Games/FTL Advanced Edition/start.sh" ""
Categories=Game;
Path=/home/set/Downloads/Games/FTL Advanced Edition
```

- Run rofi, select "Sample"

## What behaviour you see

- Nothing

## What behaviour you expect to see

- The application being launched

**Additional details:**

This is the default desktop entry provided by the game FTL. It starts fine using `gtk-launch`; however, rofi fails silently when trying to open it using `rofi -show drun`.  When the directory is renamed to `FTL_Advanced_Edition` and the corresponding `Exec` line is changed, rofi launches the application normally.

You can test this with any desktop file that has spaces in the Exec line.

If rofi isn't going to support files like this, it should at the very least print a warning or error instead of failing silently.

**Comment by DaveDavenport** [comment] 2020-12-28 20:40
I tried to reproduce this, but for me it works with spaces in directory.

I tried the following:

```ini
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=FTL: Advanced Edition
GenericName=FTL: Advanced Edition
Comment=FTL: Advanced Edition
Exec="/home/qball/Downloads/Test 3/gedit" "~/mytest.txt"
Categories=Game;
Path=/home/qball/Downloads/Test 3
```

**Comment by DaveDavenport** [comment] 2021-05-29 11:46
Closing as I cannot reproduce.

**Closed by DaveDavenport** 2021-05-29 11:46 UTC
Labels: bug
