### ISSUE TITLE
[BUG] Menu spawns at the height relative to the wrong monitor

### ISSUE THREAD

**Issue by Blackilykat** [davatorium/rofi#1905] opened 2023-10-06 14:10 UTC
### Rofi version (rofi -v)

Version: 1.7.3

### Configuration

https://gist.github.com/Blackilykat/2e1322e0334596bd165c81160fa7aad2

### Theme

https://gist.github.com/Blackilykat/e1b0379de2a297d8833b00c9c50074cd

### Timing report

https://gist.github.com/Blackilykat/c0d2864c2a9b0b209f65328b037a0299

### Launch command

rofi -mod drun,run -show drun

### Step to reproduce

* Have multiple monitors with different resolutions, so that there is a blank space in the corner
* Launch rofi in both monitors
* The output will be offset in one of them

### Expected behavior

The menu spawns in the middle of the used monitor
![rofi-fixed](https://github.com/davatorium/rofi/assets/66535696/b03cc68c-4c7c-4589-9be9-8ec2beeeff86)

### Actual behavior

The menu spawns in the middle of the used monitor, but with the height of the middle of the unused monitor
![rofi](https://github.com/davatorium/rofi/assets/66535696/5ffae9dd-3bfc-4206-9eaf-2df80e6c9dae)

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment] 2023-10-06 15:57
```css
element-icon {
    size:           Tem ;
    vertical-align: 0.50;
}
```
This is not valid? in your theme.

**Comment by DaveDavenport** [comment] 2023-10-06 15:58
Can you please post the output of `rofi -h`
(it contains detected monitor layout)

I am not able to reproduce it with 4k+fhd monitor.

**Comment by Blackilykat** [comment] 2023-10-06 16:36
> ```css
> element-icon {
>     size:           Tem ;
>     vertical-align: 0.50;
> }
> 
> This is not valid? in your theme.

I'm not sure, but when I don't add `>> output.txt` to the command it shows up weird. I'm using rounded-purple-dark from [newmanls/rofi-themes-collection](https://github.com/newmanls/rofi-themes-collection)
![error](https://github.com/davatorium/rofi/assets/66535696/7c84a211-8b26-4bdb-87df-d22e11e91260)

[here](https://gist.github.com/Blackilykat/d548206957cfebf3198f9b8b78a0b98a)'s the output of `rofi -h`
if it helps, I'm using i3wm

**Comment by DaveDavenport** [comment] 2023-10-06 16:42
thx for the paste.
Aah, that print is fixed in newer version.  
I am also using i3, for me it works fine (atleast with latest version, have not tested the old 1.7.3 yet).

**Comment by DaveDavenport** [comment] 2023-10-06 16:51
Can you try adding this at the bottom, I think it might get the behavior you want:

```css
window {
   anchor: center;
   location: center;
}
```
This makes sure that the center of rofi is centered on the center of the monitor, even if your window resizes (and you have dynamic size window).

**Comment by DaveDavenport** [comment] 2023-10-06 16:53
https://davatorium.github.io/rofi/guides/Positioning/theme3-positioning/

**Comment by DaveDavenport** [comment] 2023-10-06 17:04
This has been fixed and should work as expected without extra config entry in 1.7.5.

I am confused about this:

![image](https://github.com/davatorium/rofi/assets/406245/578f40eb-22fd-490c-a54a-8de98798dc7a)

**Closed as completed by DaveDavenport** 2023-10-06 17:04 UTC
Labels: bug

**Comment by Blackilykat** [comment] 2023-10-06 17:48
My bad - I saw the latest version was over a year old and assumed it would be the same as the latest on apt without checking version numbers. I reinstalled using the version on github and the issue is fixed, thanks
