### ISSUE TITLE
run: my_script "-10" works but run: my_script -10 doesn't

### ISSUE THREAD

**Issue by wis** [davatorium/rofi#937] opened 2019-03-21 12:23 UTC
## Version
`Version: 1.5.2
`

## Configuration

[gist](https://gist.github.com/wis/1edc1c7b27b90dc88dfd52e41516ae00)

## Launch Command
`rofi -no-config -show run`

## Steps to reproduce
my_script:
```bash my_script
notify-send "$0 $1 $2" #or other way to show output
```
* Step 1 `rofi -no-config -show run`
* Step 2 run my_script that exists in a directory which's path is in $PATH like so `my_script -10`

## What behaviour you see

* argument not supplied to script when without quotes.

`my_script +10` and `my_script "-10"` work
but `my_script -10` doesn't

## What behaviour you expect to see

* my_script arguments with no quotes to be supplied/passed to script/program

**Comment by DaveDavenport** [comment] 2019-03-21 12:51
Rofi is doing exactly as designed.

The entry box works as a filter on the list, when hitting accept key, (enter) it will execute the *matched item*, not the content of the entry box.

If you enter  `my_script -10` it will match my_script  (because it will match everything matching `my_script ` and not matching `10 `  ) and execute that.

To execute the entry command use the correct keybinding for this. Or if you do not want the - to be 'negate' change/disable the negate command (this option is available in git).

**Comment by wis** [comment] 2019-05-18 19:57
I appreciate your keystrokes Dave, good to know it's by design and not a bug, haven't you though of this use case (entering command lines, which can include command option `-`/dashes) when you designed it?
I just ran into this issue again, using rofi in dmenu mode, by the way, and I couldn't find what is the shortcut that you mentioned by reading the manual, is there a reason (can break something) that wouldn't allow adding an option like `-no-negate` or a `-matching` algorithm/method to disable it?

also is there an option that starts rofi with a given filter string already in the input field? 
like fzf's -q option
```
        -q, --query=STR
              Start the finder with the given query
```

**Comment by DaveDavenport** [comment] 2019-05-19 17:03
Sorry, manpage should be fixed.

**Comment by DaveDavenport** [comment] 2019-05-19 17:17
Added `-matching-negate-char`.

**Closed** 2019-05-19 17:16 UTC
