### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lega4e** [davatorium/rofi#1576] opened 2022-01-28 09:17 UTC
### Rofi version (rofi -v)

1.6.1

### Configuration

https://github.com/nvxden/profile/blob/master/rofi.rasi

### Launch command

rofi -show run

### Step to reproduce

```bash
$ rofi -show run
$ # (type in rofy): echo Hello World<Enter>
Hello World # We can see in console
$ rofi -show run # again
$ # (type in rofy): echo Hello<Enter>
Hello World # NOO!
```
It's becouse focus always stays on the top of suggests. Probably, Ctrl+Enter can help but it does't works.

### Expected behavior

When I press Enter must be executed command that I have written, is't command from first suggest.

### Actual behavior

Executes command from first suggest.

**Comment by DaveDavenport** [comment] 2022-01-28 09:26
1.) You are on a very old version. --> see guidelines
2.) The behavior you describe is correct behavior for rofi.
**The entry box is a filter for what is in the list,  and will execute the selected item, not what you entered.**
You can tweak your usecase:
* Ctrl-Enter (accept-custom binding) does execute the entered text (tested on latest version and works). 
* Disable history so what you entered manually previously is not stored between sessions.

closing, not a bug.

**Closed as completed by DaveDavenport** 2022-01-28 09:26 UTC
Labels: bug, Incomplete Report - Please follow the guidelines
