### ISSUE TITLE
Rofi doesn't receive keyboard input when there is no terminal opened on the same workspace (Gnome)

### ISSUE THREAD

**Issue by jesk78** [davatorium/rofi#975] opened 2019-06-04 11:06 UTC
## Version

1.5.1 (Gnome - Fedora release 30 (Thirty))

## Configuration

[https://gist.github.com/jesk78/2d2ba60240f2a21191d0c96007c6bb6a](https://gist.github.com/jesk78/2d2ba60240f2a21191d0c96007c6bb6a)

## Launch Command

rofi -show run

## Steps to reproduce

Gnome in Fedora release 30 (Thirty) 

Open up "rofi -show run" with your configured shortcut and try to type without having any window opened on the same workspace. 

## What behaviour you see

Rofi will only be able to receive your keyboard input if a terminal window is opened on same workspace. On the other hand Rofi will accept mouse input just fine.

## What behaviour you expect to see

Accepting keyboard input as soon as you start Rofi / receiving keyboard input focus when you start up Rofi.

**Comment by sardemff7** [comment] 2019-06-04 11:14
Probably Wayland-related. Duplicate of #446.

**Closed by sardemff7** 2019-06-04 11:14 UTC
Labels: XWayland, duplicate
